### ISSUE TITLE
On windows, empty lines are added in .known_hosts

### ISSUE THREAD

**Issue by Mindiell** [cbrews/ignition#10]
Thus, the reading of this file becomes impossible and no more requests can be done without an error.

For now, I delete the file before any requests, but I don't like it :)

**Comment by cbrews** [comment]
Thanks for the note here--I'll take a review of this and see if I can provide a quick fix!

**Comment by cbrews** [comment]
@Mindiell -- a new release [0.1.4](https://github.com/cbrews/ignition/releases/tag/0.1.4) has been created with this problem fixed.  Please let me know if you continue to run into problems.

Upgrade should be graceful, the `.known_hosts` parsing has been made more resilient.
