### ISSUE TITLE
SuccessResponse.data() doesn't catch unicode decode errors

### ISSUE THREAD

**Issue by pinnaculum** [cbrews/ignition#30]
Hi,

Thanks to all involved in this beautiful project.

I added gemini support to [galacteek](https://gitlab.com/galacteek/galacteek) by using ignition. I noticed no problem at all with ignition except when downloading files which have a different content type than *text/gemini*.

Was browsing the great **Library of Eris**:  gemini://libraryoferis.org/cgi-bin/books.cgi and, when downloading a PDF, response.data() (from SuccessResponse) raised an error (it tried to decode it as unicode).

[This patch fixes the issue](https://gitlab.com/cipres/ignition/-/commit/a17002fca29d3f6cd72b78ce5e522fd48671e7b3#680cb6570f50dba8d68b33ac2bc70ddd5fafff10). You guys are the gemini experts and you probably know a more elegant way to fix the problem, just wanted to raise the issue.

Keep it up.

**Comment by cbrews** [comment]
@pinnaculum thanks for this patch and note!  I'll have some time to review this request this week and hopefully be able to pull in a fix and get a new release out!

**Comment by cbrews** [comment]
@pinnaculum  this change was committed here.  I'll release v0.1.8 shortly.

**Comment by pinnaculum** [comment]
@cbrews Thanks a lot for merging the fix. Do you think there could be other areas in ignition where unicode decoding could be a problem ? The unit tests look great.

**Comment by cbrews** [comment]
No major concerns at this time with regards to the spec, only 2x responses should be decoded.  But if you run into problems please advise!
