### ISSUE TITLE
Expose Server Certificate in BaseResponse

### ISSUE THREAD

**Issue by n0ot** [cbrews/ignition#6]
It would be nice if the certificate received from the server could be exposed in ignition.BasicResponse, so clients can display information about the certificate.

**Comment by cbrews** [comment]
Thank you for the feature request!  I will start reviewing this.  In the meantime, if you have a proposed API recommendation or working solution, please open a PR and we can see if will be sufficient.

**Comment by cbrews** [comment]
@n0ot -- I've created #7 to address this issue.  Please review and let me know if you have any feedback.

**Comment by cbrews** [comment]
#7 has been merged.  Additional questions opened as separate tickets.
